person:
    name: zhangsan
    age: 18


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db4?useUnicode=true&characterEncoding=utf8
    username: root
    password: rootroot
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  type-aliases-package: com.k.bean
  mapper-locations: classpath:mapper/*Mapper.xml

